# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/risc_v_soc_test/risc_v_soc_test.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==risc_v_soc_test || ORIG_REF_NAME==risc_v_soc_test} -quiet] -quiet

# IP: bd/risc_v_soc_test/ip/risc_v_soc_test_risc_v_top_0_0/risc_v_soc_test_risc_v_top_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==risc_v_soc_test_risc_v_top_0_0 || ORIG_REF_NAME==risc_v_soc_test_risc_v_top_0_0} -quiet] -quiet

# IP: bd/risc_v_soc_test/ip/risc_v_soc_test_AHB_Lite_gpio_0_0/risc_v_soc_test_AHB_Lite_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==risc_v_soc_test_AHB_Lite_gpio_0_0 || ORIG_REF_NAME==risc_v_soc_test_AHB_Lite_gpio_0_0} -quiet] -quiet

# IP: bd/risc_v_soc_test/ip/risc_v_soc_test_AHB_Lite_IIC_0_0/risc_v_soc_test_AHB_Lite_IIC_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==risc_v_soc_test_AHB_Lite_IIC_0_0 || ORIG_REF_NAME==risc_v_soc_test_AHB_Lite_IIC_0_0} -quiet] -quiet

# IP: bd/risc_v_soc_test/ip/risc_v_soc_test_AHB_Lite_SPI_LCD_0_0/risc_v_soc_test_AHB_Lite_SPI_LCD_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==risc_v_soc_test_AHB_Lite_SPI_LCD_0_0 || ORIG_REF_NAME==risc_v_soc_test_AHB_Lite_SPI_LCD_0_0} -quiet] -quiet

# IP: bd/risc_v_soc_test/ip/risc_v_soc_test_AHB_M2S_cmtcnt_pipe_0_0/risc_v_soc_test_AHB_M2S_cmtcnt_pipe_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==risc_v_soc_test_AHB_M2S_cmtcnt_pipe_0_0 || ORIG_REF_NAME==risc_v_soc_test_AHB_M2S_cmtcnt_pipe_0_0} -quiet] -quiet

# IP: bd/risc_v_soc_test/ip/risc_v_soc_test_S0_AHB_Slave_pipe_0_0/risc_v_soc_test_S0_AHB_Slave_pipe_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==risc_v_soc_test_S0_AHB_Slave_pipe_0_0 || ORIG_REF_NAME==risc_v_soc_test_S0_AHB_Slave_pipe_0_0} -quiet] -quiet

# IP: bd/risc_v_soc_test/ip/risc_v_soc_test_My_Concat_4_0_0/risc_v_soc_test_My_Concat_4_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==risc_v_soc_test_My_Concat_4_0_0 || ORIG_REF_NAME==risc_v_soc_test_My_Concat_4_0_0} -quiet] -quiet

# IP: bd/risc_v_soc_test/ip/risc_v_soc_test_My_Concat_4_0_1/risc_v_soc_test_My_Concat_4_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==risc_v_soc_test_My_Concat_4_0_1 || ORIG_REF_NAME==risc_v_soc_test_My_Concat_4_0_1} -quiet] -quiet

# IP: bd/risc_v_soc_test/ip/risc_v_soc_test_xlconcat_0_0/risc_v_soc_test_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==risc_v_soc_test_xlconcat_0_0 || ORIG_REF_NAME==risc_v_soc_test_xlconcat_0_0} -quiet] -quiet

# IP: bd/risc_v_soc_test/ip/risc_v_soc_test_xlconcat_1_0/risc_v_soc_test_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==risc_v_soc_test_xlconcat_1_0 || ORIG_REF_NAME==risc_v_soc_test_xlconcat_1_0} -quiet] -quiet

# XDC: bd/risc_v_soc_test/risc_v_soc_test_ooc.xdc
